source "https://rubygems.org"

gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-archives"
gem "jekyll-redirect-from"
gem "jekyll-include-cache"
gem "jekyll-emoji"
gem "jekyll-asset-pipeline"
gem "jekyll-analytics"
gem "jekyll-optional-front-matter"
gem "jekyll-remote-theme"
gem "jekyll-gist"
gem "jekyll-mentions"